### PR TITLE
Fix for maps that don't have a sky specified in the NMAPINFO.

### PR DESCRIPTION
**Pull request by Petethegoat**
If you think there's better default behaviour than falling back to SKY1, let me know!

### CODE REVIEW

**Comment by jmickle66666666** [comment]
Yeah this should be fine for now. PRBoom+ will crash out if no SKY1 is defined, maybe we can handle the case of there being no sky defined in the texture1 lump eventually. Not sure what the result would be in that case though?

**Comment by Petethegoat** [comment]
I suppose you could just have it default to a black texture from nasty.wad?

**Comment by jmickle66666666** [comment]
The trouble is then you need to merge the TEXTURE1 lumps from nasty.wad into whatever wad you're using. It would be fine for patches but not textures. ZDoom will automatically merge TEXTURE1 definitions across wads, but most wads targetting PRBoom+ and lower will not expect this behaviour, and instead redefine all the textures from the IWAD it is targeting. (If you load any boom-compatible wad you will likely see every doom 2 texture defined in it's texture1 (if it has one))

**Comment by jmickle66666666** [comment]
I think taking the zdoom approach is probably the best bet.

**Pull request merged**
